### ISSUE TITLE
[BUG]: Error serializing `.stars` returned from `getStaticProps` in "/".

### ISSUE THREAD

**Issue by tcmonster** [AykutSarac/jsoncrack.com#426]
### Issue description

get error when run dev:

```
> json-crack@0.0.0 dev /Volumes/ResSSD/Projects/community/jsoncrack.com
> next dev

  ▲ Next.js 14.2.10
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 1608ms
 ○ Compiling / ...
(node:14101) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Compiled / in 11.9s (1389 modules)
 ⨯ N [Error]: Error serializing `.stars` returned from `getStaticProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at r (/Volumes/ResSSD/Projects/community/jsoncrack.com/node_modules/.pnpm/next@14.2.10_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:446)
    at /Volumes/ResSSD/Projects/community/jsoncrack.com/node_modules/.pnpm/next@14.2.10_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:683
    at Array.every (<anonymous>)
    at r (/Volumes/ResSSD/Projects/community/jsoncrack.com/node_modules/.pnpm/next@14.2.10_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:580)
    at $ (/Volumes/ResSSD/Projects/community/jsoncrack.com/node_modules/.pnpm/next@14.2.10_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:8:1100)
    at e8 (/Volumes/ResSSD/Projects/community/jsoncrack.com/node_modules/.pnpm/next@14.2.10_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:19:294)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doRender (/Volumes/ResSSD/Projects/community/jsoncrack.com/node_modules/.pnpm/next@14.2.10_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1407:30)
    at async cacheEntry.responseCache.get.routeKind (/Volumes/ResSSD/Projects/community/jsoncrack.com/node_modules/.pnpm/next@14.2.10_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1581:28)
    at async /Volumes/ResSSD/Projects/community/jsoncrack.com/node_modules/.pnpm/next@14.2.10_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/response-cache/index.js:90:36
    at async /Volumes/ResSSD/Projects/community/jsoncrack.com/node_modules/.pnpm/next@14.2.10_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/lib/batcher.js:45:32 {
  page: '/'
}
 ○ Compiling /_error ...
 ✓ Compiled /_error in 3.3s (1389 modules)
 GET / 500 in 16649ms
 ```

### Operating system

- OS: [e.g. iOS]: MacOS M1 Max
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by tcmonster** [comment]
it's fixed. it was my fault.
